/**
 * Writes the committed brand assets in public/ from the mark defined in
 * src/lib/brand-mark.ts: favicon.svg, favicon.ico and apple-touch-icon.png.
 * Run with `bun run icons:build` after editing the mark; the outputs are
 * committed, so this never runs at build or request time.
 *
 * The 16px frame is rendered with the loop slightly thickened (see
 * LOOP_SMALL_STROKE) — the usual favicon trade of exact fidelity for
 * legibility. Every frame sits on a solid brand-brown tile so the mark reads
 * on any tab-bar color, the same way paseo.sh's own favicon does.
 *
 * It also writes plugin/shared/brand-mark.ts: the same mark as a white-on-
 * transparent PNG data URI. The companion plugin cannot render SVG (the Paseo
 * SDK whitelists no SVG module), but React Native's <Image> can tint a
 * monochrome PNG with the host theme's foreground color, which gives the
 * plugin the same theme-following mark the website header has.
 */
import { writeFileSync } from "node:fs"
import { join } from "node:path"
import { Resvg } from "@resvg/resvg-js"
import {
  BRAND_BROWN,
  BRAND_CREAM,
  brandMarkSvg,
} from "../src/lib/brand-mark.ts"

// Scripts are always invoked via `bun run` from the repo root (see package.json).
const PUBLIC_DIR = join(process.cwd(), "public")
const PLUGIN_SHARED_DIR = join(process.cwd(), "plugin", "shared")

const ICO_SIZES = [16, 32, 48] as const
const APPLE_TOUCH_SIZE = 180
/** Rendered size of the plugin PNG. Displayed at ~22pt, so this covers 3x screens. */
const PLUGIN_MARK_SIZE = 96

function tile(small: boolean): string {
  return brandMarkSvg({
    ink: BRAND_CREAM,
    background: BRAND_BROWN,
    small,
    title: "paseo.cafe",
  })
}

function render(svg: string, size: number): Buffer {
  const resvg = new Resvg(svg, { fitTo: { mode: "width", value: size } })
  return resvg.render().asPng()
}

/** Packs PNG frames into an .ico. PNG-compressed frames are read by every current browser. */
function packIco(frames: { size: number; png: Buffer }[]): Buffer {
  const directory = Buffer.alloc(6 + frames.length * 16)
  directory.writeUInt16LE(0, 0) // reserved
  directory.writeUInt16LE(1, 2) // type: icon
  directory.writeUInt16LE(frames.length, 4)

  let offset = directory.length
  frames.forEach((frame, index) => {
    const entry = 6 + index * 16
    // 256px is encoded as 0 in this field; nothing here is that large.
    directory.writeUInt8(frame.size, entry)
    directory.writeUInt8(frame.size, entry + 1)
    directory.writeUInt8(0, entry + 2) // palette entries
    directory.writeUInt8(0, entry + 3) // reserved
    directory.writeUInt16LE(1, entry + 4) // color planes
    directory.writeUInt16LE(32, entry + 6) // bits per pixel
    directory.writeUInt32LE(frame.png.length, entry + 8)
    directory.writeUInt32LE(offset, entry + 12)
    offset += frame.png.length
  })

  return Buffer.concat([directory, ...frames.map((frame) => frame.png)])
}

const full = tile(false)
const small = tile(true)

writeFileSync(join(PUBLIC_DIR, "favicon.svg"), full)

const frames = ICO_SIZES.map((size) => ({
  size,
  png: render(size <= 16 ? small : full, size),
}))
writeFileSync(join(PUBLIC_DIR, "favicon.ico"), packIco(frames))
writeFileSync(
  join(PUBLIC_DIR, "apple-touch-icon.png"),
  render(full, APPLE_TOUCH_SIZE)
)

const pluginPng = render(brandMarkSvg({ ink: "#ffffff" }), PLUGIN_MARK_SIZE)
writeFileSync(
  join(PLUGIN_SHARED_DIR, "brand-mark.ts"),
  `// Generated by scripts/build-icons.ts from src/lib/brand-mark.ts — do not edit.
// Run \`bun run icons:build\` at the repo root after changing the mark.

/** The paseo.cafe mark, white on transparent, for tinting with <Image tintColor>. */
export const BRAND_MARK_PNG =
  "data:image/png;base64,${pluginPng.toString("base64")}"

/** Pixel size of BRAND_MARK_PNG (square). */
export const BRAND_MARK_PNG_SIZE = ${PLUGIN_MARK_SIZE}
`
)

console.log(
  `Wrote favicon.svg, favicon.ico (${ICO_SIZES.join(", ")}px) and apple-touch-icon.png (${APPLE_TOUCH_SIZE}px) to public/, and brand-mark.ts to plugin/shared/`
)
